### ISSUE TITLE
你好，运行了您的程序，报错

### ISSUE THREAD

**Issue by postyear** [golango-cn/go-music#1]
core\search.go:94:9:  undefined: From/where/First，这三个是search下的，不知道是哪来的，

**Comment by golango-cn** [comment]
报错信息发一下

**Comment by golango-cn** [comment]
@postyear 报错信息发下
另外，这个程序是从http://mp34.butterfly.mopaasapp.com网站上查的下载音乐地址，刚试下这个网站有更新现在程序不能正常下载，需要改下提取地址正则和cookies，最近有点忙没空更新。

**Comment by postyear** [comment]
> @postyear 获取下最新版本，把操作系统和错误信息发下，现在我这边windows和mac都是正常的

谢谢您的关心，问题我昨晚已经解决，做了一些优化，准备引用您的项目

**Comment by golango-cn** [comment]
> > @postyear 获取下最新版本，把操作系统和错误信息发下，现在我这边windows和mac都是正常的
> 
> 谢谢您的关心，问题我昨晚已经解决，做了一些优化，准备引用您的项目

好的，多多交流
